In [5]:
import pandas as pd

In [28]:
#url for reading the SS table with state names and abbreviations
url = "https://www.ssa.gov/international/coc-docs/states.html"

#url for reading the data from worldometers data showing covid deaths in every US state
url1 = "https://www.worldometers.info/coronavirus/country/us/"

In [29]:
state_abbreviations = pd.read_html(url)

In [30]:
print(state_abbreviations)

[                       0   1
0                ALABAMA  AL
1                 ALASKA  AK
2         AMERICAN SAMOA  AS
3                ARIZONA  AZ
4               ARKANSAS  AR
5             CALIFORNIA  CA
6               COLORADO  CO
7            CONNECTICUT  CT
8               DELAWARE  DE
9   DISTRICT OF COLUMBIA  DC
10               FLORIDA  FL
11               GEORGIA  GA
12                  GUAM  GU
13                HAWAII  HI
14                 IDAHO  ID
15              ILLINOIS  IL
16               INDIANA  IN
17                  IOWA  IA
18                KANSAS  KS
19              KENTUCKY  KY
20             LOUISIANA  LA
21                 MAINE  ME
22              MARYLAND  MD
23         MASSACHUSETTS  MA
24              MICHIGAN  MI
25             MINNESOTA  MN
26           MISSISSIPPI  MS
27              MISSOURI  MO
28               MONTANA  MT
29              NEBRASKA  NE
30                NEVADA  NV
31         NEW HAMPSHIRE  NH
32            NEW JERSEY  NJ
33            NEW MEXICO  NM
34              NEW YORK  NY
35        NORTH CAROLINA  NC
36          NORTH DAKOTA  ND
37   NORTHERN MARIANA IS  MP
38                  OHIO  OH
39              OKLAHOMA  OK
40                OREGON  OR
41          PENNSYLVANIA  PA
42           PUERTO RICO  PR
43          RHODE ISLAND  RI
44        SOUTH CAROLINA  SC
45          SOUTH DAKOTA  SD
46             TENNESSEE  TN
47                 TEXAS  TX
48                  UTAH  UT
49               VERMONT  VT
50              VIRGINIA  VA
51        VIRGIN ISLANDS  VI
52            WASHINGTON  WA
53         WEST VIRGINIA  WV
54             WISCONSIN  WI
55               WYOMING  WY]

In [31]:
type(state_abbreviations)

list

In [32]:
df = state_abbreviations[0]

In [33]:
state_abbreviations_df = pd.DataFrame(df)

In [34]:
state_abbreviations_df.head()

                0   1
0         ALABAMA  AL
1          ALASKA  AK
2  AMERICAN SAMOA  AS
3         ARIZONA  AZ
4        ARKANSAS  AR

In [35]:
state_abbreviations_df.rename(columns={0: "state", 1: "state_abbreviation"})

                   state state_abbreviation
0                ALABAMA                 AL
1                 ALASKA                 AK
2         AMERICAN SAMOA                 AS
3                ARIZONA                 AZ
4               ARKANSAS                 AR
5             CALIFORNIA                 CA
6               COLORADO                 CO
7            CONNECTICUT                 CT
8               DELAWARE                 DE
9   DISTRICT OF COLUMBIA                 DC
10               FLORIDA                 FL
11               GEORGIA                 GA
12                  GUAM                 GU
13                HAWAII                 HI
14                 IDAHO                 ID
15              ILLINOIS                 IL
16               INDIANA                 IN
17                  IOWA                 IA
18                KANSAS                 KS
19              KENTUCKY                 KY
20             LOUISIANA                 LA
21                 MAINE                 ME
22              MARYLAND                 MD
23         MASSACHUSETTS                 MA
24              MICHIGAN                 MI
25             MINNESOTA                 MN
26           MISSISSIPPI                 MS
27              MISSOURI                 MO
28               MONTANA                 MT
29              NEBRASKA                 NE
30                NEVADA                 NV
31         NEW HAMPSHIRE                 NH
32            NEW JERSEY                 NJ
33            NEW MEXICO                 NM
34              NEW YORK                 NY
35        NORTH CAROLINA                 NC
36          NORTH DAKOTA                 ND
37   NORTHERN MARIANA IS                 MP
38                  OHIO                 OH
39              OKLAHOMA                 OK
40                OREGON                 OR
41          PENNSYLVANIA                 PA
42           PUERTO RICO                 PR
43          RHODE ISLAND                 RI
44        SOUTH CAROLINA                 SC
45          SOUTH DAKOTA                 SD
46             TENNESSEE                 TN
47                 TEXAS                 TX
48                  UTAH                 UT
49               VERMONT                 VT
50              VIRGINIA                 VA
51        VIRGIN ISLANDS                 VI
52            WASHINGTON                 WA
53         WEST VIRGINIA                 WV
54             WISCONSIN                 WI
55               WYOMING                 WY

# Scrapping data from Worldometer

In [46]:
## Reading data from worldometer site. The data is held in an object named df1 

from urllib.request import Request, urlopen

req = Request("https://www.worldometers.info/coronavirus/country/us/", headers={'User-Agent': 'Mozilla/5.0'})
webpage = urlopen(req).read()


tables = pd.read_html(webpage)
df1 = tables[0]
print(df1.head())

     #    USAState  TotalCases  NewCases  TotalDeaths  NewDeaths  \
0  NaN   USA Total    85430891   93156.0    1030323.0      225.0
1  1.0  California     9508467    4161.0      91432.0        6.0
2  2.0       Texas     6906900    4248.0      88777.0       16.0
3  3.0     Florida     6146564   12120.0      74400.0        NaN
4  4.0    New York     5559628    8015.0      69395.0       26.0

   TotalRecovered  ActiveCases  Tot Cases/1M pop  Deaths/1M pop    TotalTests  \
0      81849223.0    2551345.0          258097.0         3113.0  1.023662e+09
1       9048705.0     368330.0          240646.0         2314.0  1.655536e+08
2       6721363.0      96760.0          238203.0         3062.0  6.508263e+07
3       5877677.0     194487.0          286183.0         3464.0  5.811293e+07
4       5390788.0      99445.0          285790.0         3567.0  1.105116e+08

   Tests/ 1M pop  Population                            Source    Projections
0      3092611.0         NaN                               NaN            NaN
1      4189935.0  39512223.0              [view by county] [1]  [projections]
2      2244547.0  28995881.0      [view by county] [1] [2] [3]  [projections]
3      2705729.0  21477737.0  [view by county] [1] [2] [3] [4]  [projections]
4      5680791.0  19453561.0      [view by county] [1] [2] [3]  [projections]

In [49]:
#converting df1 into a dataframe named state_covid_data
state_covid_data = pd.DataFrame(df1)

In [50]:
state_data.head(55)

,#,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop,Population,Source,Projections
0,NaN,USA Total,85427777,92711.0,1030186.0,205.0,81849015.0,2548576.0,258088.0,3112.0,1.023662e+09,3092611.0,NaN,NaN,NaN
1,1.0,California,9508467,4161.0,91432.0,6.0,9048705.0,368330.0,240646.0,2314.0,1.655536e+08,4189935.0,39512223.0,[view by county] [1],[projections]
2,2.0,Texas,6906900,4248.0,88777.0,16.0,6721363.0,96760.0,238203.0,3062.0,6.508263e+07,2244547.0,28995881.0,[view by county] [1] [2] [3],[projections]
3,3.0,Florida,6146564,12120.0,74400.0,NaN,5877677.0,194487.0,286183.0,3464.0,5.811293e+07,2705729.0,21477737.0,[view by county] [1] [2] [3] [4],[projections]
4,4.0,New York,5559628,8015.0,69395.0,26.0,5390788.0,99445.0,285790.0,3567.0,1.105116e+08,5680791.0,19453561.0,[view by county] [1] [2] [3],[projections]
5,5.0,Illinois,3274360,6406.0,38114.0,11.0,3072280.0,163966.0,258397.0,3008.0,5.789805e+07,4569040.0,12671821.0,[1] [2] [3] [4] [5],[projections]
6,6.0,Pennsylvania,2907324,3381.0,45147.0,1.0,2782876.0,79301.0,227099.0,3527.0,2.639074e+07,2061456.0,12801989.0,[view by county] [1],[projections]
7,7.0,North Carolina,2744935,4163.0,24644.0,3.0,2674444.0,45847.0,261719.0,2350.0,2.635621e+07,2512967.0,10488084.0,[1] [2] [3] [4],[projections]
8,8.0,Ohio,2743577,NaN,38590.0,NaN,2656694.0,48293.0,234712.0,3301.0,2.227260e+07,1905416.0,11689100.0,[view by county] [1] [2],[projections]
9,9.0,Georgia,2556044,3317.0,38198.0,10.0,2472019.0,45827.0,240741.0,3598.0,2.516814e+07,2370456.0,10617423.0,[1] [2],[projections]
10,10.0,Michigan,2501863,NaN,36218.0,NaN,2383521.0,82124.0,250516.0,3627.0,2.525680e+07,2529004.0,9986857.0,[1] [2] [3] [4],[projections]
11,11.0,New Jersey,2370508,4852.0,33651.0,11.0,2166378.0,170479.0,266883.0,3789.0,1.779410e+07,2003347.0,8882190.0,[view by county] [1],[projections]
12,12.0,Tennessee,2053638,NaN,26403.0,NaN,2014546.0,12689.0,300715.0,3866.0,1.290118e+07,1889127.0,6829174.0,[1] [2] [3] [4],[projections]
13,13.0,Arizona,2049627,1643.0,30299.0,6.0,1991231.0,28097.0,281592.0,4163.0,1.953448e+07,2683780.0,7278717.0,[1] [2],[projections]
14,14.0,Massachusetts,1855500,3709.0,20544.0,11.0,1783298.0,51658.0,269206.0,2981.0,4.496906e+07,6524344.0,6892503.0,[1],[projections]
15,15.0,Virginia,1770620,3488.0,20358.0,10.0,1675689.0,74573.0,207441.0,2385.0,1.917253e+07,2246206.0,8535519.0,[1] [2],[projections]
16,16.0,Indiana,1727818,1188.0,23692.0,5.0,1577453.0,126673.0,256649.0,3519.0,1.990569e+07,2956781.0,6732219.0,[1] [2] [3],[projections]
17,17.0,Wisconsin,1664367,2590.0,14527.0,NaN,1588701.0,61139.0,285854.0,2495.0,1.646760e+07,2828301.0,5822434.0,[1] [2] [3] [4] [5],[projections]
18,18.0,Washington,1565696,4785.0,12888.0,NaN,1476257.0,76551.0,205610.0,1692.0,1.399090e+07,1837308.0,7614893.0,[view by county] [1],[projections]
19,19.0,Minnesota,1500556,1518.0,12920.0,19.0,1474158.0,13478.0,266073.0,2291.0,1.947901e+07,3453951.0,5639632.0,[1] [2] [3],[projections]
20,20.0,South Carolina,1495762,NaN,17905.0,NaN,1450015.0,27842.0,290512.0,3478.0,1.650782e+07,3206202.0,5148714.0,[1] [2] [3] [4],[projections]
21,21.0,Missouri,1440814,NaN,20454.0,NaN,1396060.0,24300.0,234759.0,3333.0,1.463219e+07,2384091.0,6137428.0,[1] [2] [3] [4] [5] [6] [7] [8],[projections]
22,22.0,Colorado,1426298,1948.0,13308.0,4.0,1354252.0,58738.0,247676.0,2311.0,1.781300e+07,3093213.0,5758736.0,[1] [2],[projections]
23,23.0,Kentucky,1349478,1201.0,15917.0,1.0,1303034.0,30527.0,302054.0,3563.0,1.367528e+07,3060940.0,4467673.0,[1] [2] [3] [4],[projections]
24,24.0,Alabama,1310513,770.0,19651.0,1.0,1271536.0,19326.0,267278.0,4008.0,7.688520e+06,1568066.0,4903185.0,[1] [2] [3],[projections]
25,25.0,Louisiana,1254640,1547.0,17319.0,1.0,1220875.0,16446.0,269885.0,3725.0,1.572636e+07,3382889.0,4648794.0,[view by county] [1] [2] [3],[projections]
26,26.0,Maryland,1078122,1983.0,14581.0,12.0,1012619.0,50922.0,178329.0,2412.0,2.098897e+07,3471730.0,6045680.0,[1] [2],[projections]
27,27.0,Oklahoma,1045574,NaN,14419.0,NaN,1028534.0,2621.0,264236.0,3644.0,5.473577e+06,1383274.0,3956971.0,[1] [2] [3] [4],[projections]
28,28.0,Utah,943368,NaN,4765.0,NaN,927320.0,11283.0,294255.0,1486.0,9.406861e+06,2934181.0,3205958.0,[1] [2] [3],[projections]
29,29.0,Iowa,876666,313.0,9588.0,NaN,846205.0,20873.0,277859.0,3039.0,8.492575e+06,2691723.0,3155070.0,[1] [2] [3] [4] [5] [6],[projections]
30,30.0,Arkansas,841675,556.0,11461.0,10.0,826446.0,3768.0,278903.0,3798.0,6.918869e+06,2292683.0,3017804.0,[1] [2] [3] [4] [5],[projections]
31,31.0,Mississippi,805800,505.0,12466.0,1.0,784615.0,8719.0,270753.0,4189.0,6.396772e+06,2149345.0,2976149.0,[1] [2] [3],[projections]
32,32.0,Connecticut,803748,1642.0,10937.0,NaN,739734.0,53077.0,225437.0,3068.0,1.553471e+07,4357212.0,3565287.0,[1] [2] [3],[projections]
33,33.0,Kansas,782802,NaN,8802.0,NaN,764353.0,9647.0,268698.0,3021.0,2.269976e+06,779173.0,2913314.0,[1] [2] [3] [4] [5] [6] [7] [8] [9] [10],[projections]
34,34.0,Oregon,755367,NaN,7598.0,NaN,699486.0,48283.0,179093.0,1801.0,1.144566e+07,2713696.0,4217737.0,[1] [2] [3],[projections]
35,35.0,Nevada,735021,894.0,10872.0,NaN,703305.0,20844.0,238631.0,3530.0,6.875532e+06,2232203.0,3080156.0,[1] [2],[projections]
36,36.0,New Mexico,531309,NaN,7700.0,NaN,509507.0,14102.0,253387.0,3672.0,7.165488e+06,3417297.0,2096829.0,[1] [2] [3] [4],[projections]
37,37.0,West Virginia,512571,641.0,6933.0,1.0,503481.0,2157.0,286009.0,3869.0,6.172615e+06,3444257.0,1792147.0,[1],[projections]
38,38.0,Nebraska,484085,NaN,4240.0,NaN,474572.0,5273.0,250250.0,2192.0,5.506012e+06,2846355.0,1934408.0,[1] [2] [3] [4] [5],[projections]
39,39.0,Idaho,449682,NaN,4939.0,NaN,440606.0,4137.0,251632.0,2764.0,2.939835e+06,1645063.0,1787065.0,[1] [2] [3],[projections]
40,40.0,Rhode Island,389901,596.0,3565.0,NaN,365970.0,20366.0,368053.0,3365.0,7.974599e+06,7527745.0,1059361.0,[1] [2],[projections]
41,41.0,New Hampshire,322904,NaN,2526.0,NaN,315914.0,4464.0,237480.0,1858.0,4.808903e+06,3536710.0,1359711.0,[1] [2] [3],[projections]
42,42.0,Montana,276192,NaN,3385.0,NaN,271565.0,1242.0,258418.0,3167.0,2.789012e+06,2609534.0,1068778.0,[1] [2] [3] [4],[projections]
43,43.0,Hawaii,274495,1275.0,1451.0,5.0,245995.0,27049.0,193870.0,1025.0,3.806440e+06,2688407.0,1415872.0,[1] [2] [3] [4] [5],[projections]
44,44.0,Delaware,273722,515.0,2942.0,NaN,259016.0,11764.0,281097.0,3021.0,1.026007e+06,1053651.0,973764.0,[1] [2],[projections]
45,45.0,Maine,261031,560.0,2345.0,1.0,239689.0,18997.0,194189.0,1745.0,5.255256e+06,3909544.0,1344212.0,[1] [2],[projections]
46,46.0,Alaska,249522,NaN,1252.0,NaN,243048.0,5222.0,341089.0,1711.0,4.107614e+06,5614985.0,731545.0,[1],[projections]
47,47.0,North Dakota,243345,NaN,2276.0,NaN,239789.0,1280.0,319324.0,2987.0,6.181210e+05,811116.0,762062.0,[1] [2],[projections]
48,48.0,South Dakota,239110,NaN,2919.0,NaN,234945.0,1246.0,270285.0,3300.0,2.182151e+06,2466658.0,884659.0,[1],[projections]
49,49.0,Wyoming,157409,NaN,1820.0,NaN,NaN,NaN,271977.0,3145.0,1.396443e+06,2412823.0,578759.0,[1] [2],[projections]
50,50.0,District Of Columbia,147819,NaN,1342.0,NaN,140013.0,6464.0,209450.0,1902.0,3.067883e+06,4346989.0,705749.0,[1] [2] [3],[projections]
51,51.0,Vermont,129854,NaN,654.0,NaN,119639.0,9561.0,208103.0,1048.0,3.639448e+06,5832552.0,623989.0,[1] [2],[projections]
52,52.0,Puerto Rico,646707,6748.0,4330.0,13.0,514514.0,127863.0,190941.0,1278.0,4.253969e+06,1255991.0,3386941.0,[1] [2] [3] [4] [5],NaN
53,53.0,Guam,48865,38.0,362.0,1.0,48264.0,239.0,NaN,NaN,4.591000e+05,NaN,NaN,[1] [2] [3],NaN
54,54.0,United States Virgin Islands,19252,86.0,113.0,NaN,18192.0,947.0,NaN,NaN,4.157720e+05,NaN,NaN,[1] [2],NaN

In [55]:
#cleaning data by removing columns that are not needed
#and removing  row with USA total as it is not needed row [0]
state_data.drop(columns = ['#', 'NewCases', 'NewDeaths','Source', 'Projections'], axis = 1)
state_data.drop([0])

,#,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop,Population,Source,Projections
1,1.0,California,9508467,4161.0,91432.0,6.0,9048705.0,368330.0,240646.0,2314.0,1.655536e+08,4189935.0,39512223.0,[view by county] [1],[projections]
2,2.0,Texas,6906900,4248.0,88777.0,16.0,6721363.0,96760.0,238203.0,3062.0,6.508263e+07,2244547.0,28995881.0,[view by county] [1] [2] [3],[projections]
3,3.0,Florida,6146564,12120.0,74400.0,NaN,5877677.0,194487.0,286183.0,3464.0,5.811293e+07,2705729.0,21477737.0,[view by county] [1] [2] [3] [4],[projections]
4,4.0,New York,5559628,8015.0,69395.0,26.0,5390788.0,99445.0,285790.0,3567.0,1.105116e+08,5680791.0,19453561.0,[view by county] [1] [2] [3],[projections]
5,5.0,Illinois,3274360,6406.0,38114.0,11.0,3072280.0,163966.0,258397.0,3008.0,5.789805e+07,4569040.0,12671821.0,[1] [2] [3] [4] [5],[projections]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,60.0,Navajo Nation,53946,NaN,1777.0,NaN,51995.0,174.0,NaN,NaN,5.292480e+05,NaN,NaN,[1] [2] [3],NaN
61,61.0,Grand Princess Ship,122,NaN,7.0,NaN,115.0,0.0,NaN,NaN,NaN,NaN,NaN,[1],NaN
62,62.0,Wuhan Repatriated,3,NaN,NaN,NaN,3.0,0.0,NaN,NaN,3.000000e+00,NaN,NaN,NaN,NaN
63,63.0,Diamond Princess Ship,46,NaN,NaN,NaN,46.0,0.0,NaN,NaN,4.600000e+01,NaN,NaN,NaN,NaN
64,NaN,Total:,85427777,92711.0,1030186.0,205.0,81849015.0,2548576.0,258088.0,3112.0,1.023662e+09,3092611.0,NaN,NaN,NaN

In [42]:
state_data.head(55)

,#,USAState,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,ActiveCases,Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/ 1M pop,Population,Source,Projections
0,NaN,USA Total,85422723,92398.0,1030170.0,205.0,81848776.0,2543777.0,258073.0,3112.0,1.023662e+09,3092611.0,NaN,NaN,NaN
1,1.0,California,9508467,4161.0,91432.0,6.0,9048705.0,368330.0,240646.0,2314.0,1.655536e+08,4189935.0,39512223.0,[view by county] [1],[projections]
2,2.0,Texas,6906900,4248.0,88777.0,16.0,6721363.0,96760.0,238203.0,3062.0,6.508263e+07,2244547.0,28995881.0,[view by county] [1] [2] [3],[projections]
3,3.0,Florida,6146564,12120.0,74400.0,NaN,5877677.0,194487.0,286183.0,3464.0,5.811293e+07,2705729.0,21477737.0,[view by county] [1] [2] [3] [4],[projections]
4,4.0,New York,5559628,8015.0,69395.0,26.0,5390788.0,99445.0,285790.0,3567.0,1.105116e+08,5680791.0,19453561.0,[view by county] [1] [2] [3],[projections]
5,5.0,Illinois,3274360,6406.0,38114.0,11.0,3072280.0,163966.0,258397.0,3008.0,5.789805e+07,4569040.0,12671821.0,[1] [2] [3] [4] [5],[projections]
6,6.0,Pennsylvania,2907324,3381.0,45147.0,1.0,2782876.0,79301.0,227099.0,3527.0,2.639074e+07,2061456.0,12801989.0,[view by county] [1],[projections]
7,7.0,North Carolina,2744935,4163.0,24644.0,3.0,2674444.0,45847.0,261719.0,2350.0,2.635621e+07,2512967.0,10488084.0,[1] [2] [3] [4],[projections]
8,8.0,Ohio,2743577,NaN,38590.0,NaN,2656694.0,48293.0,234712.0,3301.0,2.227260e+07,1905416.0,11689100.0,[view by county] [1] [2],[projections]
9,9.0,Georgia,2556044,3317.0,38198.0,10.0,2472019.0,45827.0,240741.0,3598.0,2.516814e+07,2370456.0,10617423.0,[1] [2],[projections]
10,10.0,Michigan,2501863,NaN,36218.0,NaN,2383521.0,82124.0,250516.0,3627.0,2.525680e+07,2529004.0,9986857.0,[1] [2] [3] [4],[projections]
11,11.0,New Jersey,2370508,4852.0,33651.0,11.0,2166378.0,170479.0,266883.0,3789.0,1.779410e+07,2003347.0,8882190.0,[view by county] [1],[projections]
12,12.0,Tennessee,2053638,NaN,26403.0,NaN,2014546.0,12689.0,300715.0,3866.0,1.290118e+07,1889127.0,6829174.0,[1] [2] [3] [4],[projections]
13,13.0,Arizona,2049627,1643.0,30299.0,6.0,1991231.0,28097.0,281592.0,4163.0,1.953448e+07,2683780.0,7278717.0,[1] [2],[projections]
14,14.0,Massachusetts,1855500,3709.0,20544.0,11.0,1783298.0,51658.0,269206.0,2981.0,4.496906e+07,6524344.0,6892503.0,[1],[projections]
15,15.0,Virginia,1770620,3488.0,20358.0,10.0,1675689.0,74573.0,207441.0,2385.0,1.917253e+07,2246206.0,8535519.0,[1] [2],[projections]
16,16.0,Indiana,1727818,1188.0,23692.0,5.0,1577453.0,126673.0,256649.0,3519.0,1.990569e+07,2956781.0,6732219.0,[1] [2] [3],[projections]
17,17.0,Wisconsin,1664367,2590.0,14527.0,NaN,1588701.0,61139.0,285854.0,2495.0,1.646760e+07,2828301.0,5822434.0,[1] [2] [3] [4] [5],[projections]
18,18.0,Washington,1565696,4785.0,12888.0,NaN,1476257.0,76551.0,205610.0,1692.0,1.399090e+07,1837308.0,7614893.0,[view by county] [1],[projections]
19,19.0,Minnesota,1500556,1518.0,12920.0,19.0,1474158.0,13478.0,266073.0,2291.0,1.947901e+07,3453951.0,5639632.0,[1] [2] [3],[projections]
20,20.0,South Carolina,1495762,NaN,17905.0,NaN,1450015.0,27842.0,290512.0,3478.0,1.650782e+07,3206202.0,5148714.0,[1] [2] [3] [4],[projections]
21,21.0,Missouri,1440814,NaN,20454.0,NaN,1396060.0,24300.0,234759.0,3333.0,1.463219e+07,2384091.0,6137428.0,[1] [2] [3] [4] [5] [6] [7] [8],[projections]
22,22.0,Colorado,1426298,1948.0,13308.0,4.0,1354252.0,58738.0,247676.0,2311.0,1.781300e+07,3093213.0,5758736.0,[1] [2],[projections]
23,23.0,Kentucky,1349478,1201.0,15917.0,1.0,1303034.0,30527.0,302054.0,3563.0,1.367528e+07,3060940.0,4467673.0,[1] [2] [3] [4],[projections]
24,24.0,Alabama,1310513,770.0,19651.0,1.0,1271536.0,19326.0,267278.0,4008.0,7.688520e+06,1568066.0,4903185.0,[1] [2] [3],[projections]
25,25.0,Louisiana,1254640,1547.0,17319.0,1.0,1220875.0,16446.0,269885.0,3725.0,1.572636e+07,3382889.0,4648794.0,[view by county] [1] [2] [3],[projections]
26,26.0,Maryland,1078122,1983.0,14581.0,12.0,1012619.0,50922.0,178329.0,2412.0,2.098897e+07,3471730.0,6045680.0,[1] [2],[projections]
27,27.0,Oklahoma,1045574,NaN,14419.0,NaN,1028534.0,2621.0,264236.0,3644.0,5.473577e+06,1383274.0,3956971.0,[1] [2] [3] [4],[projections]
28,28.0,Utah,943368,NaN,4765.0,NaN,927320.0,11283.0,294255.0,1486.0,9.406861e+06,2934181.0,3205958.0,[1] [2] [3],[projections]
29,29.0,Iowa,871612,NaN,9572.0,NaN,845966.0,16074.0,276258.0,3034.0,8.492575e+06,2691723.0,3155070.0,[1] [2] [3] [4] [5] [6],[projections]
30,30.0,Arkansas,841675,556.0,11461.0,10.0,826446.0,3768.0,278903.0,3798.0,6.918869e+06,2292683.0,3017804.0,[1] [2] [3] [4] [5],[projections]
31,31.0,Mississippi,805800,505.0,12466.0,1.0,784615.0,8719.0,270753.0,4189.0,6.396772e+06,2149345.0,2976149.0,[1] [2] [3],[projections]
32,32.0,Connecticut,803748,1642.0,10937.0,NaN,739734.0,53077.0,225437.0,3068.0,1.553471e+07,4357212.0,3565287.0,[1] [2] [3],[projections]
33,33.0,Kansas,782802,NaN,8802.0,NaN,764353.0,9647.0,268698.0,3021.0,2.269976e+06,779173.0,2913314.0,[1] [2] [3] [4] [5] [6] [7] [8] [9] [10],[projections]
34,34.0,Oregon,755367,NaN,7598.0,NaN,699486.0,48283.0,179093.0,1801.0,1.144566e+07,2713696.0,4217737.0,[1] [2] [3],[projections]
35,35.0,Nevada,735021,894.0,10872.0,NaN,703305.0,20844.0,238631.0,3530.0,6.875532e+06,2232203.0,3080156.0,[1] [2],[projections]
36,36.0,New Mexico,531309,NaN,7700.0,NaN,509507.0,14102.0,253387.0,3672.0,7.165488e+06,3417297.0,2096829.0,[1] [2] [3] [4],[projections]
37,37.0,West Virginia,512571,641.0,6933.0,1.0,503481.0,2157.0,286009.0,3869.0,6.172615e+06,3444257.0,1792147.0,[1],[projections]
38,38.0,Nebraska,484085,NaN,4240.0,NaN,474572.0,5273.0,250250.0,2192.0,5.506012e+06,2846355.0,1934408.0,[1] [2] [3] [4] [5],[projections]
39,39.0,Idaho,449682,NaN,4939.0,NaN,440606.0,4137.0,251632.0,2764.0,2.939835e+06,1645063.0,1787065.0,[1] [2] [3],[projections]
40,40.0,Rhode Island,389901,596.0,3565.0,NaN,365970.0,20366.0,368053.0,3365.0,7.974599e+06,7527745.0,1059361.0,[1] [2],[projections]
41,41.0,New Hampshire,322904,NaN,2526.0,NaN,315914.0,4464.0,237480.0,1858.0,4.808903e+06,3536710.0,1359711.0,[1] [2] [3],[projections]
42,42.0,Montana,276192,NaN,3385.0,NaN,271565.0,1242.0,258418.0,3167.0,2.789012e+06,2609534.0,1068778.0,[1] [2] [3] [4],[projections]
43,43.0,Hawaii,274495,1275.0,1451.0,5.0,245995.0,27049.0,193870.0,1025.0,3.806440e+06,2688407.0,1415872.0,[1] [2] [3] [4] [5],[projections]
44,44.0,Delaware,273722,515.0,2942.0,NaN,259016.0,11764.0,281097.0,3021.0,1.026007e+06,1053651.0,973764.0,[1] [2],[projections]
45,45.0,Maine,261031,560.0,2345.0,1.0,239689.0,18997.0,194189.0,1745.0,5.255256e+06,3909544.0,1344212.0,[1] [2],[projections]
46,46.0,Alaska,249522,NaN,1252.0,NaN,243048.0,5222.0,341089.0,1711.0,4.107614e+06,5614985.0,731545.0,[1],[projections]
47,47.0,North Dakota,243345,NaN,2276.0,NaN,239789.0,1280.0,319324.0,2987.0,6.181210e+05,811116.0,762062.0,[1] [2],[projections]
48,48.0,South Dakota,239110,NaN,2919.0,NaN,234945.0,1246.0,270285.0,3300.0,2.182151e+06,2466658.0,884659.0,[1],[projections]
49,49.0,Wyoming,157409,NaN,1820.0,NaN,NaN,NaN,271977.0,3145.0,1.396443e+06,2412823.0,578759.0,[1] [2],[projections]
50,50.0,District Of Columbia,147819,NaN,1342.0,NaN,140013.0,6464.0,209450.0,1902.0,3.067883e+06,4346989.0,705749.0,[1] [2] [3],[projections]
51,51.0,Vermont,129854,NaN,654.0,NaN,119639.0,9561.0,208103.0,1048.0,3.639448e+06,5832552.0,623989.0,[1] [2],[projections]
52,52.0,Puerto Rico,646707,6748.0,4330.0,13.0,514514.0,127863.0,190941.0,1278.0,4.253969e+06,1255991.0,3386941.0,[1] [2] [3] [4] [5],NaN
53,53.0,Guam,48865,38.0,362.0,1.0,48264.0,239.0,NaN,NaN,4.591000e+05,NaN,NaN,[1] [2] [3],NaN
54,54.0,United States Virgin Islands,19252,86.0,113.0,NaN,18192.0,947.0,NaN,NaN,4.157720e+05,NaN,NaN,[1] [2],NaN